### PR TITLE
Fix count warning php 7.2

### PR DESCRIPTION
**Pull request by SosthenG**
[See this issue](https://github.com/portphp/portphp/issues/99)

### CODE REVIEW

**Comment by ddeboer** [comment]
Awesome, thanks for the fix!

Could you also add PHP 7.2 (and 7.3, if you want) to [our Travis testing matrix](https://github.com/portphp/spreadsheet/blob/master/.travis.yml#L3-L7)?

**Comment by ddeboer** [comment]
Thanks! We may want to give `columnHeaders` an empty array as default value, but this is a good fix for now.

**Comment by ddeboer** [comment]
Tagged as 1.0.1.

**Comment by SosthenG** [comment]
> Thanks! We may want to give `columnHeaders` an empty array as default value, but this is a good fix for now.

Yeah that's what I did first, but I thought that in case of an empty row, the condition would be true and that's probably not what's expected.

**Pull request merged**
